### ISSUE TITLE
application

### ISSUE THREAD

**Issue by luckyly** [zhangchunbin/HuanXinDemo#1]

**Comment by mycold** [comment]
FATAL EXCEPTION: main
                                                                       Process: com.art.activity:mult, PID: 22083
                                                                       java.lang.RuntimeException: Unable to create application com.art.application.MainApplication: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.execute(java.lang.Runnable)' on a null object reference
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5092)
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:186)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                           at android.os.Looper.loop(Looper.java:200)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.execute(java.lang.Runnable)' on a null object reference
                                                                           at com.hyphenate.chat.EMClient.execute(Unknown Source)
                                                                           at com.hyphenate.chat.EMClient.addConnectionListener(Unknown Source)
                                                                           at com.art.application.MainApplication.setGlobalListeners(MainApplication.java:231)
                                                                           at com.art.application.MainApplication.initHuanXin(MainApplication.java:174)
                                                                           at com.art.application.MainApplication.onCreate(MainApplication.java:167)
                                                                           at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5084)
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:186) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                           at android.os.Looper.loop(Looper.java:200) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5877) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
application 里注册连接监听时一直报空指针异常
